### ISSUE TITLE
Background of the image 

### ISSUE THREAD

**Issue by Alan29535** [dilawar/PlotDigitizer#10]
is there any way to allow this script to identify the image with a dark or transparent background?
I have tried to change the background by adding values to all pixels, but the color image convert to greyscale again and shows the error: I computed that background is 'dark' which is unacceptable to me
![0314_006_3-PEEPreduced-from_10to5](https://user-images.githubusercontent.com/65850871/151916309-296cd338-7296-4ac7-97c4-84a0b7472035.jpg)
.

**Comment by dilawar** [comment]
Related #9
