### ISSUE TITLE
Can run application from PowerShell

### ISSUE THREAD

**Issue by stepro1** [dilawar/PlotDigitizer#14]
Hello dilawar,

Thank you for your great work.
I am searching for a good application for Plot Digitalization and I was testing your application today.
I tried your examples as well as my own Plots. But in both cases I get the following error Message:

![image](https://user-images.githubusercontent.com/85225512/200033739-84b6a394-293a-4d48-9b6e-d41d872e1be9.png)

I also had a look at the Source Code but I don't understand what is the problem

**Comment by dilawar** [comment]
@stepro1 Can you also post the sample image (if possible). There are two issues here: one is Unicode related and the other is data/image related. I've not pushed the Unicode fixes (they are on a separate branch). To fix failure in the assertion, I need to have a look at the image.

**Comment by stepro1** [comment]
@dilawar I just managed to run the script with your trimmed.png example without the -l parameter. With the -l Parameter it's still not working for me and I get the same error as before.
![image](https://user-images.githubusercontent.com/85225512/200133200-e6ad913a-2488-4de1-b818-444275bf0189.png)

-> Here is an example Image that I want to process. I could not manage to process is with and without the batch-Mode
![015 - 3413_A01; 3413_L015_trimmed](https://user-images.githubusercontent.com/85225512/200133274-f944c59b-c2e1-438b-a9b5-4c201b4e917f.png)

**Comment by dilawar** [comment]
Thanks for sharing the image. I managed to fix the issue. I'll release the new version soon. Till then you can use the `master` branch.

![image](https://user-images.githubusercontent.com/895681/200176058-3434a0cd-7cf7-4256-b66a-6d020d4b5143.png)
