### ISSUE TITLE
CICD: Fix the travis deployment

### ISSUE THREAD

**Issue by KikeM** [dilawar/PlotDigitizer#5]
Hi!

The build is reported as failing, but when I have checked the Travis pipeline one can see that it works correctly until the end. 

The reason to report as broken is this line in your deployment script defined in `.travis.yml`:
```bash
sh -e /etc/init.d/xvfb start
```

What is the need behind this line?

Cheers

**Comment by dilawar** [comment]
- Fixed Travis and also bumped the version after removing deprecation warnings.
- Formatted source code using `black`.

The CI issue summarised well here https://benlimmer.com/2019/01/14/travis-ci-xvfb/ and official instructions are here https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui .

Unfortunately, I could fix is satisfactory. So instead `--plot` showing up the plot, it takes an additional filename and saves the plot to this file.

**Comment by KikeM** [comment]
Great, I am glad your pipeline is up again ;)

**Comment by dilawar** [comment]
Thanks for reporting. The Travis CI was broken for a year after they made changes to their YAML parser.
